# The URL the site will be built for
base_url = "https://lifelogsearch.org/lsc"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "juice"

[markdown.highlighting]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
light_theme = "github-light"
dark_theme = "github-dark"

[extra]
# Put all your custom variables here
juice_logo_name = "LSC'26 at ICMR'26"
juice_logo_path = ""
